
--REMEMBER TO CHANGE YOUR SQL NAMING TO CAMEL CASE
CREATE DATABASE cryptopile;


CREATE TABLE accounts (
   userId SERIAL PRIMARY KEY ,
   firstName VARCHAR(255) NOT NULL,
   lastName VARCHAR(255) NOT NULL,
   email VARCHAR(255) NOT NULL,
   password VARCHAR(255) NOT NULL,
   verificationCode INTEGER NOT NULL,
   isVerifiedEmail BOOLEAN NOT NULL,
   UNIQUE (email) 
);

CREATE TABLE admin (
adminId SERIAL NOT NULL,
adminFirstName VARCHAR(200) NOT NULL,
adminLastName VARCHAR(200) NOT NULL,
adminEmail VARCHAR(200) NOT NULL,
adminCode INTEGER NOT NULL,
adminPassword VARCHAR(200) NOT NULL
);


-- DROP TABLE todo;
CREATE TABLE todo (
    todoId SERIAL PRIMARY KEY,
    userId INTEGER NOT NULL,
    userName VARCHAR(100) NOT NULL,
    description VARCHAR(600) NOT NULL,
    iv VARCHAR(60) NOT NULL,
    timeOfAdd TIME,
    dateOfAdd TIMESTAMP
);

CREATE TABLE imageUrl (
     imageUrlId SERIAL PRIMARY KEY,
     imageUrlCategory VARCHAR (50) NOT NULL,
     imageUrlOwnerId INTEGER NOT NULL DEFAULT 20221501, 
     imageUrls VARCHAR(250) NOT NULL
);



-- DROP THESE COLUMNS 
ALTER TABLE todo DROP dateOfAdd;
ALTER TABLE todo DROP timeOfAdd;

-- ADD THESE COLUMNS AGAIN WITH RIGHT DATA TYPES AND CONSTRAINTS
ALTER TABLE todo ADD COLUMN dateOfAdd VARCHAR(20) NOT NULL DEFAULT 'Sun Feb 13 2022';     
ALTER TABLE todo ADD COLUMN timeOfAdd VARCHAR(20) NOT NULL DEFAULT '4:30:42 PM'; 