name: Deploy To Render
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
<<<<<<< HEAD
      - name: deploy
        uses: johnbeynon/render-deploy-action
=======
      - uses: actions/johnbeynon/render-deploy-action
>>>>>>> c31205bedd301f19adef52d1d6eb9d27b2940cdc
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
